//MUST MOVE STATE BASED TABLE IN FUTURE 
export enum PropertyFees {
    COSMETICALLY_INCOMPLETE_AIRCRAFT = 2000,
    COSMETICALLY_COMPLETE_AIRCRAFT = 4000,
    SCRAP_AIRCRAFT = 8000,
    SALVAGE_AIRCRAFT = 10000,
    REPAIRABLE_AIRCRAFT = 12000,
    USABLE_AIRCRAFT = 14000,
    NEW_UNUSED_AIRCRAFT = 30000
}

export enum SpecialPropertyAmericanSurplusFees {
    COSMETICALLY_INCOMPLETE_AIRCRAFT = 200,
    COSMETICALLY_COMPLETE_AIRCRAFT = 400,
    SCRAP_AIRCRAFT = 500,
    SALVAGE_AIRCRAFT = 1000,
    REPAIRABLE_AIRCRAFT = 2000,
    USABLE_AIRCRAFT = 3500,
    NEW_UNUSED_AIRCRAFT = 6000

}