server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    root /opt/cdn-ui;
    try_files /index.html =404;
    add_header Cache-Control "no-cache";
  }

  location = /index.html {
    root /opt/cdn-ui;
    try_files /index.html =404;
    add_header Cache-Control "no-cache";
  }

  location = /image-index.json {
    root /usr/share/nginx/html;
    try_files /image-index.json =404;
    add_header Cache-Control "no-cache, no-store, must-revalidate";
  }

  location / {
    autoindex on;
    try_files $uri $uri/ =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location /ui/ {
    alias /opt/cdn-ui/;
    index index.html;
    autoindex off;
    add_header Cache-Control "no-cache";
    try_files $uri $uri/ /ui/index.html;
  }

  location = /healthz {
    add_header Content-Type text/plain;
    return 200 "ok";
  }
}
