input {
  heartbeat {
    interval => 60
    message => "local-bootstrap-heartbeat"
  }
}

filter {
  mutate {
    add_field => { "bootstrap_source" => "american-surplus-api" }
  }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-bootstrap-%{+YYYY.MM.dd}"
  }
}
