import DoneeAccount from "@/organization/models/DoneeAccount";
import Property from "@/properties/models/Property";
import { NotificationType } from "../services/notification-factory.service";
import Application from "@/eligibility/models/Application.entity";
import Request from '@/properties/models/Request';
import Compliance from "@/compliance-utilization/models/Compliance.entity";
import LegacyPropertyData from "@/data-migration/models/LegacyPropertyData.model";
import Sba8aCertification from "@/organization/models/Sba8aCertification.entity";

export interface INotificationPayloadMap {
    [NotificationType.APPLICATION_SUBMITTED]: { application: Application };
    [NotificationType.APPLICATION_REVIEWED]: { application: Application };
    [NotificationType.PROPERTY_REQUESTED_VIA_ICN]: { property: Property; doneeAccount: DoneeAccount };
    [NotificationType.PROPERTY_ADDED_TO_REQUEST]: { requestId: number; icn: string; doneeAccount: DoneeAccount };
    [NotificationType.REQUEST_UPDATED]: { property: Property; updatedBy: string };
    [NotificationType.REQUEST_QUANTITY_UPDATED]: { property: Property; updatedBy: string; oldQuantity: number; newQuantity: number };
    [NotificationType.TCN_UPDATED]: { requestId: number };
    [NotificationType.COMMENT_ADDED]: { requestId: number; userName: string };
    [NotificationType.ATTACHMENT_UPLOADED]: { request: Request; doneeAccount: DoneeAccount; userName: string };
    [NotificationType.LOAR_GENERATED]: { request: Request };
    [NotificationType.LOAR_SHIPPING_UPDATED]: { requestId: number };
    [NotificationType.PROPERTIES_ALLOCATED]: { request: Request; allocatedPropertyList: { property_name: string; ICN: string; allocated_quantity: number }[] };
    [NotificationType.PROPERTIES_DENIED]: { requestId: number };
    [NotificationType.PROPERTIES_CANCELED_SASP]: { requestId: number };
    [NotificationType.PROPERTIES_CANCELED_DONEE]: { requestId: number };
    [NotificationType.PROPERTIES_UN_CANCELED]: { requestId: number };
    [NotificationType.PROPERTIES_PICKED_UP]: { requestId: number };
    [NotificationType.INVOICE_GENERATED]: { request: Request; updatedBy: string };
    [NotificationType.INVOICE_SIGNED]: { request: Request };
    [NotificationType.INVOICE_CANCELED]: { requestId: number; tcn?: string };
    [NotificationType.INVOICE_PAYMENT_REQUESTED]: { request: Request };
    [NotificationType.INVOICE_PAID]: { request: Request };
    [NotificationType.COMPLIANCE_IN_SERVICE_WARNING]: { property: Property };
    [NotificationType.COMPLIANCE_PERIOD_WARNING]: { compliance: Compliance };
    [NotificationType.COMPLIANCE_OVERDUE]: { property: Property };
    [NotificationType.COMPLIANCE_EVIDENCE_SUBMITTED]: { property: Property };
    [NotificationType.COMPLIANCE_EVIDENCE_APPROVED]: { property: Property };
    [NotificationType.COMPLIANCE_EVIDENCE_REJECTED]: { property: Property };
    [NotificationType.ELIGIBILITY_ATTACHMENT_UPLOADED]: { application: Application; formId: number; fileName: string };
    [NotificationType.ELIGIBILITY_ATTACHMENT_REMOVED]: { application: Application; formId: number };
    [NotificationType.ELIGIBILITY_STATUS_CHANGED]: { application: Application; oldStatus: string; newStatus: string };
    [NotificationType.ELIGIBILITY_EXPIRATION_WARNING]: { application: Application; daysUntilExpiry: number };
    [NotificationType.ELIGIBILITY_EXPIRED]: { application: Application };
    [NotificationType.LEGACY_PROPERTY_MIGRATION_REQUESTED]: { legacyProperty: LegacyPropertyData, doneeAccount: DoneeAccount };
    [NotificationType.EXPIRED_SCREENING_DATE]: { property: Property };
    [NotificationType.EXPIRED_SCREENING_DATE_TODAY]: { property: Property };
    [NotificationType.EXPIRED_SCREENING_DATE_THREE_DAYS_FROM_NOW]: { property: Property };
    [NotificationType.FEE_CHANGE_NOTIFICATION]: { stateId: number; effectiveDate: string; fees: Array<{ disposalConditionCode: string; disposalConditionName: string; fee: number }> };
    [NotificationType.SBA8A_EXPIRATION_WARNING]: { certification: Sba8aCertification; daysUntilExpiry: number };
    [NotificationType.SBA8A_EXPIRED]: { certification: Sba8aCertification };
    [NotificationType.WANT_LIST_MATCH_FOUND]: { matchIds: number[]; doneeAccountId: number; keyword: string };
}
