export enum DocumentTemplateEnum {
  FL_INVOICE = 'FL_Invoice',
  ELIGIBILITY_APPLICATION = 'ELIGIBILITY_APPLICATION',
  LOGISTICS_PACKET = 'LOGISTICS_PACKET',
  LOAR = 'LOAR',
  SF97 = 'SF97',
  RECONCILIATION_AGREEMENT = 'RECONCILIATION_AGREEMENT',
  REPORT_3040 = 'REPORT_3040',
}
