name: Automated - devskynetacr Create Image/Deploy to Dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '.github/**'

permissions:
  id-token: write
  contents: read

jobs:
  dev-build:
    if: ${{ github.ref_name == 'dev' }}
    runs-on: ubuntu-latest
    environment: development 

    env:
      ENV_NAME: dev
      ENV_REPO: "ENV_development-american-surplus"
      HELM_REPO: "american-surplus-helm"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create image variable
      run: | 
        REPO_NAME=${GITHUB_REPOSITORY##*/}
        IMAGE_TAG="tag-${GITHUB_SHA::7}"
        IMAGE_PATH="devskynetacr.azurecr.io/${REPO_NAME}:${IMAGE_TAG}"

        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "IMAGE_PATH=$IMAGE_PATH" >> $GITHUB_ENV
        echo "REGISTRY_NAME=devskynetacr" >> $GITHUB_ENV

    - name: Azure Authentication
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to ACR
      run: | 
        az acr login --name $REGISTRY_NAME

    - name: Docker Build
      run: | 
        docker build --build-arg ENVIRONMENT=development . -t $IMAGE_PATH

    - name: Push image
      run: | 
        docker push $IMAGE_PATH

    - name: Generate GitHub App Token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.GH_APP_ID }}
        owner: AmericanSurplus
        repositories: ${{ env.ENV_REPO }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Check out Env repo
      uses: actions/checkout@v4
      with:
        repository: AmericanSurplus/${{ env.ENV_REPO }}
        path: ${{ env.ENV_REPO }}
        token: ${{ steps.generate-token.outputs.token }}

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Update acr_tag in values.yaml
      run: |
        yq eval ".american_surplus_api.acr_tag = \"${{ env.IMAGE_TAG }}\"" -i $ENV_REPO/helm/$ENV_NAME-values.yaml

    - name: Update and push env file
      run: |
        cd $ENV_REPO
        git config user.name "github-actions"
        git config user.email "ozturkgokalp000@gmail.com"
        git add -u
        git commit -m "Update american_surplus_api acr_tag to ${{ env.IMAGE_TAG }}" || echo "Nothing to commit."
        git push || echo "Nothing to push."

    - name: Generate Helm GitHub App Token
      id: helm-generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.GH_APP_ID }}
        owner: AmericanSurplus
        repositories: ${{ env.HELM_REPO }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Automatic Helm Upgrade Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ steps.helm-generate-token.outputs.token }}
        repository: AmericanSurplus/${{ env.HELM_REPO }}
        event-type: automatic-helm-upgrade-dev
        client-payload: >-
          {
            "environment": "development"
          }
